<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE stock [
<!ELEMENT stock (new-car | used-car)*>
<!ELEMENT new-car (model, price)>
<!ELEMENT used-car (model, price, mileage, condition?)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT mileage (#PCDATA)>
<!ELEMENT condition (#PCDATA)>
]>
<stock>
    <new-car>
        <model>Mustang Shelby GT350R</model>
        <price>62070</price>
    </new-car>
    <used-car>
        <model>BMW X6</model>
        <price>31.900</price>
        <mileage>5000</mileage>
        <condition>Perfect!</condition>
    </used-car>
    <used-car>
        <model>Porsche Cayenne</model>
        <price>46.900</price>
        <mileage>98696</mileage>
    </used-car>
</stock>